### ISSUE TITLE
Set web_widget_radio_tree as optional (because is in OCA/web)

### ISSUE THREAD

**Issue by rruebner** [blooparksystems/odoo#3]

**Comment by kaerdsar** [comment]
We removed the dependency from the widget, is not required for the solution. Will close the ticket.

**Comment by jholze** [comment]
Guys, just one thing, please add useful ticket descriptions for the tickets. Because its sometimes hard for someone like me to see what the ticket is for. Why we moved this, because even if we push something in oca, the UX should look even well. Does this mean that we remove this widget to enter the address like in our LR project with the three lines to enter the address data ?

**Comment by jholze** [comment]
Tickets should also have some useful labels for better filter-options and search.
